name: Build Workflow

on:


jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install pyinstaller
      - name: Run PyInstaller
        run: |
          python -m PyInstaller --onefile src/main.py
      - uses: actions/upload-artifact@v2
        with:
          name: Windows_version
          path: dist/main.exe
