name: Build Workflow

on:
  push:
#    branches: master

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Install requirements
        run: |
          pip install pyinstaller
      - name: Run PyInstaller
        run: |
          python -m PyInstaller --onefile src/main.py
      - uses: actions/upload-artifact@v2
        with:
          name: mac_version
          path: dist/main.dmg
