name: Build Workflow

on:
 push:


jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'
          architecture: 'x64'
      - name: Install requirements
        run: |
         python -m pip install --upgrade pip
         pip install pyinstaller
         pip install -r requirements.txt
      - name: Run PyInstaller
        run: |
          python -m PyInstaller --onefile main.py
      - uses: actions/upload-artifact@v2
        with:
          name: Windows_version
          path: dist/main.exe
